name: Delete Old Releases
on:
  schedule:
    - cron: '0 16 * * *' # Auto delete at 23:00 WIB (16:00 UTC)

jobs:
  get_latest_release_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release ID
        id: get_release
        run: |
          latest_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/fyn170/geo-sing-box/releases/latest" | jq -r '.id')
          echo "::set-output name=latest_id::$latest_id"

  delete_old_releases:
    needs: get_latest_release_id
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        if: steps.get_release.outputs.latest_id != ''
        run: |
          latest_id=${{ needs.get_latest_release_id.outputs.latest_id }}
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/fyn170/geo-sing-box/releases" | \
            jq -r '.[] | select(.id != $latest_id) | .tag_name' | \
            xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/fyn170/geo-sing-box/releases/tags/{}"
