name: Delete Old Release

on:
  schedule:
    - cron: '0 16 * * *' # Jadwal alur kerja untuk dijalankan setiap hari pukul 23:00 WIB (16:00 UTC)

jobs:
  delete_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete Old Releases
      run: |
        curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/fyn170/geo-sing-box/releases/assets/{asset_id}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
