name: Build Geo-Sing-Box

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build GeoIP
        run: |
          cd $GITHUB_WORKSPACE/GeoLite2-Country
          go build

      - name: Build GeoSite
        run: |
          cd $GITHUB_WORKSPACE/geosite
          go build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            $GITHUB_WORKSPACE/GeoLite2-Country/GeoLite2-Country
            $GITHUB_WORKSPACE/geosite/geosite
