name: Auto Sync GEO
on:
  schedule:
    - cron: '0 17 * * *'    # Auto update at 00.00 WIB (GMT+7)
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Delete Previous Tag
        run: |
          git tag -d latest
          git push origin :refs/tags/latest
        if: always()
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19.5"
      
      - name: Build geosite
        id: build_site
        run: |
          cd sing-geosite
          go run -v .
      
      - name: Build geoip
        id: build_ip
        run: |
          cd sing-geoip
          go run -v .
      
      - name: Set timezone to WIB Jakarta
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Indonesia Standard Time"

      - name: Get current time
        id: time
        run: echo "::set-output name=time::$(date +'%Y%m%d%H%M%S')"

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release
          draft: false
          prerelease: false

      - name: Release geosite.db
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sing-geosite/geosite.db
          asset_name: geosite.db
          asset_content_type: application/octet-stream

      - name: Release geoip.db
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sing-geoip/geoip.db
          asset_name: geoip.db
          asset_content_type: application/octet-stream

      - name: Release geoip-cn.db
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sing-geoip/geoip-cn.db
          asset_name: geoip-cn.db
          asset_content_type: application/octet-stream

      - name: Delete Old Release
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: fyn170/geo-sing-box
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Bot Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: fyn170/geo-sing-box
          event-type: sync-geo
